### ISSUE TITLE
Large text buffer allocation

### ISSUE THREAD

**Issue by mrichards42** [rmkit-dev/rmkit#115]
It looks like https://github.com/rmkit-dev/rmkit/commit/02d2b30c74c0022bc2ac4d2360e7ddcf7f7989f1 allocates a 128 MB static buffer. Could we make that configurable, or could it be smaller across the board? I haven't really looked at the text rendering code closely to understand how it works.

**Comment by raisjn** [comment]
ugh, my bad. should be much smaller

**Comment by raisjn** [comment]
0068f865189b99f15e04a2e8def5640dc813f3dc fixes it to 512kb. can't believe i mathed so bad

**Comment by raisjn** [comment]
actually, i'm going to move this from static to malloc all the way: 2646e4c851f1ee478bd042421ff42d0f7b2d919d, as the complexity for having static path is causing issues

**Comment by raisjn** [comment]
what i was trying to solve with these set of diffs is the following:

the current rendering code (stb_text) allocates a buffer on the stack via:

```
char text_buffer[a][b*font_size]
```

but if a*b*font_size gets too large, then the program segfaults (presumably the size > the stack). i am able to repro this by creating a large word (let's say 30+ characters) with no spacing and large font size and trying to render it. 

my issue with heap alloc is that i was afraid it was going to be too slow / cause fragmentation, so i tried to use a static buffer (should have used stack alloc'd buffer probably). the impl. was complicated / had a branch in it, though, so i moved back to malloc.

one question is: should i have put this diff up for review (since it was labeled w. [rmkit] and would affect others) and then it could have been caught by someone who maths.
