### ISSUE TITLE
[remux] Allow apps to be started without gui

### ISSUE THREAD

**Issue by dorianim** [rmkit-dev/rmkit#155]
Hi!

I really love remux, and I'd like to suggest one more feature:
Starting an app, but leaving the framebuffer at the current one. Like this, apps like [goMarkableStream](https://github.com/owulveryck/goMarkableStream) could be started without getting a blank screen and having to go back every time :)

**Comment by dorianim** [comment]
I just realized that this would also require to disable the freezing of this app.

**Comment by raisjn** [comment]
thanks for the idea! I need to see how close remux is to supporting this, it may be possible

**Comment by raisjn** [comment]
i think you can accomplish this by making two scripts:

1) this script starts goMarkableStream by using `setsid <command>` (which will make a new process group for your app). i'm unsure if this will work, because the docs say "setsid will make a new process group if this process is not already a process group leader" - remux uses setsid to make each program a process group leader
2) a separate script that calls `killall goRemarkableStream` to kill the process

if that doesn't work, i will look at remux's code and see how we can configure remux to not stop applications when switching between different apps.

**Comment by dorianim** [comment]
Thanks! I'll try that :)

**Comment by raisjn** [comment]
any luck? am curious if it worked or if remux needs some modifications

**Comment by raisjn** [comment]
recently, what i've done for myself is write a small script like the following:

```
setsid /opt/bin/myapp &
echo "back" > /run/remux.api
```

this will launch the program (and make it not managed by remux), then it will return to the previous screen. you can even put some text on the screen before returning using `fbink` or `simple`:

```
setsid /opt/bin/myapp
fbink "Launcher myapp"
echo "back" > /run/remux.api
```

**Comment by dorianim** [comment]
Sorry for not replying and thenks for the hint!
I haven't been able to use remux fore a while because I upgraded to 2.11.0.442 but it looks like this version is supported by toltec now :)
So I'll try it out soon
