### ISSUE TITLE
[remux] Weird behavior with and after autosleep

### ISSUE THREAD

**Issue by mariusdkm** [rmkit-dev/rmkit#158]
I'm having really weird issues after I let the remarkable 2 go automatically to sleep.(I think sleep and suspend are the same thing, so whenever I write sleep, I probably mean suspend, correct me if I'm wrong though)  
I don't know whether xochitl or remux initiates the sleep, but if I leave my rm2 out open for a while it goes to sleep as expected, since I have `Auto sleep` under Settings > Battery enabled(I didn't change any remux configs).

Now I think just xochitl goes to sleep, bc I get my expected sleepscreen but it's in a very weird aspect ratio and the wifi and cloud symbols  are still there but both disabled.  
The powerbutton in that state is unresponsive, so to get xochitl out of sleep one has to restart it through the remux gui( which still startable through the swipe up).
xochitl then seems to work as normal, except, that the wifi doesn't work at all.
But if you try to go to sleep/suspend now with the powerbutton the sleep window appears(as expected), but after 30 sec, xochitl goes out of sleep again and you again in your normal xochitl gui.

I think the wifi issue is kind of related to #157 where installing `rm2-suspend-fix` fixed it

I have installed on my Remarkable with software version 2.10.3.379:
* remux - 0.1.11-1
* rm2fb-client - 0.0.10-1
* display - 0.0.10-1
* ddvk-hacks - 26.02-1
* rm2-suspend-fix - 0.0.0-2
* [remarkable_news to change suspend screen](https://github.com/evidlo/remarkable_news)

**Comment by raisjn** [comment]
you can try turning off remux's power management (take a look at the README). it may also be the case that there are two xochitl running (remarkable_news likely restarts xochitl using systemctl)

**Comment by mariusdkm** [comment]
How can I check if there are 2 xochitl running?

**Comment by raisjn** [comment]
use `ps` and look for xochitl twice (maybe `ps | grep xochitl`)

**Comment by mariusdkm** [comment]
Nope `htop`  shows only one xochitl running and `ps | grep xochitl` also just returns one.
![Screenshot 2021-11-25 at 15 07 45](https://user-images.githubusercontent.com/43829743/143455921-500c2e79-5eea-49fd-a245-fdbf4683543f.png)
`remarkable_news` doesn't restart `xochitl` as far as I know, it needs a ddvk-hacks patch to reload the suspend image

**Comment by raisjn** [comment]
i think try turning off remux's power management, then

**Comment by mariusdkm** [comment]
Ok turning off remux's power management works, but shouldn't remux's power management harmonize with xochitl's?

**Comment by raisjn** [comment]
maybe we should add ability to tell remux not to do power management while certain apps are open (xochitl), but power management is difficult because there's now two state machines: remux/xochitl and its hard for them to co-exist correctly.

some weird examples:

* when remux puts machine to sleep, then it wakes up, xochitl will now put it to sleep  (or vice versa)
* if you use another app for 30 minute then switch to xochitl, xochitl will immediately put the tablet to sleep
* etc

i run remux+xochitl with stock sleep screen and generally don't run into the power management issues you've described, so it's tricky from device to device. (maybe there is a timing issue due to resizing the custom image before showing it, for example)

**Comment by raisjn** [comment]
i'll put up a binary later today if you can test it (it will specifically not manage power while xochitl is managing power)

**Comment by raisjn** [comment]
please try this binary when you have a chance: https://raisjn.net/remux.custom_power. it defaults to not managing power for xochitl

**Comment by raisjn** [comment]
should be fixed in stable, please re-open if it isn't

**Comment by murchu27** [comment]
Just an observation I had, not sure if this has to do with remux.

If I switch to another application (e.g., `nao`), let the tablet go to autosleep, then wake it up with the power button, that application resumes without issue. But when I go back to `xochitl`, `xochitl` immediately goes to sleep (or was already asleep), and I have to press the power button again to resume it.

I also have Auto sleep enabled in the reMarkable settings, and I'm not using a `remux.conf` anywhere. You mentioned in an earlier comment that [remux's power management can be turned off](https://github.com/rmkit-dev/rmkit/issues/158#issuecomment-979248831). I don't know how to do that, but in any case I think this issue warrants changing the default settings, rather than requiring the user to take extra steps

**Comment by raisjn** [comment]
i think this is an issue with xochitl: it is suspended (no user activity) when another app is focused. when you return after xochitl's idle timeout, it will go straight to sleep. two ways that this could be fixed: 1) actually kill xochitl (so switching back requires a restart of xochitl), 2) raising xochitl's sleep timeout to a higher number.

there may be other ways of fooling xochitl into thinking input is arriving on a regular basis, but i'm not aware of them currently

**Comment by murchu27** [comment]
If auto sleep is turned off in reMarkable settings / `xochitl.conf`, would `remux` be able to handle power consistently for the whole device?

**Comment by raisjn** [comment]
@murchu27: yes, but i haven't tried it before. remux tries to read the sleep timeout from xochitl.conf, so i hope sleep is separated into two settings
