### ISSUE TITLE
[total noob] can you draw monochrome / b&w images to e-ink displays?

### ISSUE THREAD

**Issue by 00000o1** [rmkit-dev/rmkit#203]
sorry i saw your article on hn: https://rmkit.dev/eink-is-so-retropunk/

found it inspiring. already have a project that runs a browser headless in a fully interactive way, and wondered...could i make this work, on an e-ink device? basically i only need a net connection and a way to draw pixels. as long as the thing can run chrome, we're good. it may be weird, it may not be proper, nor may it even work "in a friendly way"--but i think it would be cool to try, and if you folks think it's possible, i'm happy to give it a shot. 

retro web browser running on e-ink display? feck yeah!

**Comment by Eeems** [comment]
While it could technically run chrome, you'll have to cross-compile/port a lot of the dependencies for it, as well as wayland or x11. [Netsurf](https://github.com/alex0809/netsurf-reMarkable) has been ported to the device, so if you are okay with the limitations that impose on what JavaScript is supported, it would potentially solve your needs.

As for drawing images to the screen, the rmkit library has this: https://docs.rmkit.dev/#okpClass:framebuffer.FB:draw_bitmap
There are a couple different command line tools you could use as well if you just want to script it:
- https://rmkit.dev/apps/sas
- https://github.com/ddvk/remarkable-splash
- https://github.com/NiLuJe/FBInk

**Comment by raisjn** [comment]
@00000o1: like Eeems said, the issue is we've never tried compiling chrome for ARM and it likely requires an X server. 

@Eeems: do you know if QT has a browser that works on ARM architecture? would that require an X server?

**Comment by Eeems** [comment]
> @Eeems: do you know if QT has a browser that works on ARM architecture? would that require an X server?

I've done a bit of digging in the past. Qml doesn't support the full set of features needed for a proper browser, which is why I stopped trying to implement a browser in it. The solution Qt has is to use chromium underneath the covers in the Qt web engine: https://doc.qt.io/qt-5/qtwebengine-overview.html

This isn't part of the Qt embedded on the device, so I hadn't touched it yet, but it might be worth exploring again sometime soon since I've finally gotten around to sorting out how to compile Qt for the toltec toolchains.

**Comment by 00000o1** [comment]
Thank you sirs @Eeems and @raisjn! I don't think chrome requires X when running headless. There are some ARM Chromes out there but not sure if they would work on these guys. 

My app (https://github.com/dosyago/BrowserBoxPro) engages headless Chrome to provide an interface for it. The interface / client could be built for this platform it seems. 

If you folks are considering anything in this route, I would highly recommend avoiding a custom browser if possible (reason not ideological, but practical, as it makes everything much simpler). If can get Chrome to work in headless mode on this, then building the interface, and printing the bitmaps of the capture viewport screenshots should be possible using the e-ink display and the useful libraries you've listed for printing to the framebuffer.

Assuming I could get all the dependencies to work for this (there are quite a few for chrome, if chrome itself could work, the dependencies indeed seem like the tricky part), the interesting part of this I think is then writing the "GUI" interface in for e-ink displays. It's essentially simple: an address bar, back/forward and go buttons, a bitmap rectangle for the viewport, a button strip for the tab heads to switch tabs. You don't need much more than that for a start. More can be added of course.

I just think it would be so exciting to have a little b&w, bitmap browser actually working on e-ink. If nothing else, I think it represents a different "mode" of interaction for browsers, something more (definitely) akin to "Reader more" because of the extreme lack of distractions of having it in b&w, with a simple interface, on an e-ink display.

The project could premature from a product point of view if the concept is fundamentally flawed: perhaps a browser *is already too* "noisy" visually to be suitable for an e-ink display; or premature from an implementation / tech point of view if we can't get the build to work.

As a start, is there any way to "develop" (even if approximately) for one of these devices, while not actually on the device--like in a VM, or container, or on a particular linux flavor they use? I'm just thinking of a simple next step I could try: if there's a definite linux version used, I could try getting Chrome installed and working in that, as a kind of technical proof of concept at least. I don't know. Just an idea. 

Anyway, thank you very much for your replies, and very cool project you are doing with rmkit!!

**Comment by Eeems** [comment]
They have a custom [openembedded core linux distribution](https://www.yoctoproject.org/software-item/openembedded-core/) that they build for each release. We don't currently have emulators setup for the device at all. There are a couple simulators for some specific frameworks, but they are not enough for testing what you need.

I have a few little nitpicks with what you are talking about. You have said that we shouldn't build our own browser, then describe building a browser :laughing:, it's quite ironic. I believe what you meant to say is that we shouldn't be making our own browser engine, which I agree, that doesn't sound like much fun. Then again, I did go about building my own window compositor for the device because it seemed fun.

You also keep mentioning chrome specifically, and I think it would be better to go with chromium, or look at gecko. That said, Qt already has a web engine that could be used with a simple interface that uses headless chromium underneath the covers. Which is what I personally would be looking into when I get the chance. Along with https://github.com/mozilla/readability.

We already have a bunch of the framework setup to compile Qt modules, since we already [compile Qt itself](https://github.com/toltec-dev/toolchain/blob/v3.x/qt/Dockerfile) for the [toltec toolchain](https://github.com/toltec-dev/toolchain). In fact, we probably already build it, and just need to move it into a package and sort out how to integrate into the existing Qt install without touching the root partition.

**Comment by 00000o1** [comment]
Hey Eeems,

Your comment made my day! 😄😂 Ah, the irony of discussing whether or not to build a browser while I'm actively involved in... building a browser. Classic! I can see why you'd find that amusing. What can I say? The tech world is full of these delightful paradoxes.

Now, onto the business of architecture. When I say "highly recommend avoiding a custom browser," I can add that: "don't use as a component, modify or build" a custom, non-mainstream browser for this task. Because unless you want to redefine fun, dealing with the issues and quirks involved in doing this is not the casual weekend project most would pick. I mean, building your own window compositor does sound fun, though! 🤓

Although I've left enough room in the above that I'm sure you'll find some irony again, because using a "non-mainstream browser" as a component is exactly what I'm proposing for this! 🤣 I suppose the distinction and clarity comes out in the following way: inside, we use Chrome (a mainstream browser), and the Remote DevTools protocol / Remote Debugging Protocol, to build an "alt browser". 

As for BrowserBox, it's essentially what you're talking about with Qt. It's not really building a browser from scratch. Rather, think of it as a browser cosplay; it's dressed up to look different but underneath, it's still your run-of-the-mill browser. That's important for stability, and security. You don't want to give yourself more work than necessary, right? 🤣

Now, onto the Chrome vs. Chromium debate. You might think picking Chromium is like choosing the gluten-free, vegan option: ethical and open-source! While that's cool, I've got a different take. I favor Chrome because, in this particular use case, it brings better stability and security to the table. And as a bonus, automatic updates! The Chromium option, while commendable, might make you do some extra legwork. And who needs that, right?

Oh, and totally with you on the Qt web engine. That sounds like a great route to explore, and the Mozilla Readability project also looks promising.

Considering I've been swimming in these architectural waters for some years now, I'd love to put our heads together on this. If you're open to it, we could explore integrating BrowserBox with a Qt front-end. I think it would be a fabulous way to pool our expertise.

Whether or not we collaborate, I'm just excited about the project's potential and would be stoked to contribute in whatever capacity I can. If you want to tap into my experience, great. If not, no hard feelings. After all, the tech world is big enough for multiple visions to coexist, isn't it?

Looking forward to hearing what you think!

**Comment by 00000o1** [comment]
Sir @Eeems any reply thoughts? 🪙

**Comment by Eeems** [comment]
I unfortunately don't have the capacity to do much more than point you at resources at the moment. Feel free to ask for help on the community discord and I'll help where I can.

**Comment by 00000o1** [comment]
Thank you sir @Eeems eems! That's great 😊 you've already been very helpful--all your responses are very info-packed--I appreciate it! I'll close for now and possibly try to re-open once I have something to show. 

Once I get my hand on one of these reMarkables I will begin in earnest!

**Comment by 00000o1** [comment]
Thank you sir @Eeems! That's great 😊 you've already been very helpful--all your responses are very info-packed--I appreciate it! I'll close for now and possibly try to re-open once I have something to show.

Once I get my hand on one of these reMarkables I will begin in earnest!
