### ISSUE TITLE
[remux] Can't switch out of Koreader

### ISSUE THREAD

**Issue by sethmnielsen** [rmkit-dev/rmkit#23]
This is awesome. I especially like the multi-tasking! 

Switching from xochitl to koreader works great. However, I noticed that in order to use remux from koreader, I first have to go to the menu > Exit > Exit, then holding down the middle button will bring up remux successfully. I can switch to xochitl after this, then switch back to koreader, but I always have to exit koreader first before remux will respond to the button long press. 

Is this the "better integration with koreader" point you mentioned on the reddit post? Just thought I would outline this issue in case others weren't aware.

**Comment by raisjnn** [comment]
thank you for filing this! 

yes, this is exactly what is being referred to with "better integration". there are two main issues with the current KOReader package:

1) it sets a different bpp than other apps (uses 8 instead of 16) when invoked, so remux needs to properly adjust to that bpp when displaying. this happens in koreader.sh (and i have commented out the call to `fbdepth`  locally on my installation)
2) it does an exclusive grab of the buttons so no other apps can grab them (remux can grab first and prevent koreader from being greedy here)

we are currently deciding the best way forward: whether to try to get upstream changes in KOReader or just change remux behavior

**Comment by raisjnn** [comment]
i think we will try to make remux robust to bpp changes and will try out grabbing input away from koreader (but it may inadvertently stop koreader button controls from working)

**Comment by raisjnn** [comment]
this is also being addressed in https://github.com/Eeems/oxide/issues/69

**Comment by raisjnn** [comment]
https://github.com/koreader/koreader-base/pull/1193 and https://github.com/koreader/koreader/pull/6685 are two patches submitted for making koreader play nicer with draft, oxide and remux

**Comment by raisjnn** [comment]
both have been accepted and merged and i think they will be packaged into the 2020.10 koreader release. the latest remux builds (and toltec package) have the correct environment variables set to use the patches and should just work when the new koreader comes out. 

we have plans to bring KOReader to toltec, as well. but that may take a few days (or longer) as we figure out some logistics around the toolchain.

**Comment by raisjnn** [comment]
koreader is now in toltec, just waiting for latest release that includes the patches. based on the timing of previous releases it should be around october 15 - 20th

**Comment by raisjnn** [comment]
koreader nightly is in toltec now
