### ISSUE TITLE
[remux] See running apps

### ISSUE THREAD

**Issue by LinusCDE** [rmkit-dev/rmkit#31]
It would be really cool to see which of the apps are currently running/suspended. Maybe along with a simple memory metric to prevent opening to many apps.

As far as I gathered, killing some apps can be quite complicated, I don't find that necessary anyway.

**Comment by raisjnn** [comment]
awesome feature ideas! i think this is possible, since collecting running apps happens when figuring out what the current running app is. 

 i like the idea of killing an app too, should be doable using the process groups and maybe necessary for the crossword app (i haven't figured out how to kill it yet).

**Comment by raisjnn** [comment]
7dbe7df2cc1dff662d4004c38c958faad1577df4 is the start of this feature

i'm wondering what the UX should look like - so far it's just putting an asterisk next to the currently running apps

**Comment by LinusCDE** [comment]
That is a good idea!

One thing that would be really great, would be to see the RAM usage of all the apps. That would turn it more into a task manager (cpu stats would be useless anyway since all apps are frozen).

Something along the lines of this. Though I'm not sure whether right aligned text would be a hassle here.
![image](https://user-images.githubusercontent.com/22298664/95411655-59ce5100-0927-11eb-9ca1-baacfe9cec2f.png)

**Comment by raisjnn** [comment]
just pushed https://github.com/rmkit-dev/rmkit/commit/ad4d38966574bdea624bc87f5e022d56045043e9 which looks like:

![remux_003](https://user-images.githubusercontent.com/70462544/95643053-63f46a80-0a61-11eb-8d6b-6157cce949e5.png)

it should be on the build server (build.rmkit.dev) pretty quickly, i'll get it into toltec after its iterated on a bit more.

notice that KOReader has 0mb usage since it spawns children. we can do a slightly more thorough analysis by looking through all the pids in the process group.

**Comment by raisjnn** [comment]
i haven't addressed the other part of the mockup which is memory used / memory available. i'm inclined to use the `free` command here, but i'm afraid the numbers won't line up with what is being reported through smaps

**Comment by LinusCDE** [comment]
> i haven't addressed the other part of the mockup which is memory used / memory available. i'm inclined to use the `free` command here, but i'm afraid the numbers won't line up with what is being reported through smaps

I wouldn't mind if you'd just do that. Seeing (more or less) actual total memory used vs just the sum of the apps would be probably more helpful in my opinion.

**Comment by raisjnn** [comment]
![remux_004](https://user-images.githubusercontent.com/70462544/95668237-05dd8b00-0b26-11eb-94ef-804bf48f9ed4.png)

does this look too crowded?

**Comment by LinusCDE** [comment]
That looks really good. 👍
