### ISSUE TITLE
[minesweeper] rendering artifacts above text

### ISSUE THREAD

**Issue by raisjn** [rmkit-dev/rmkit#53]
in some places there are rendering artifacts - for example on the "open" and "flag" buttons. it is likely copying an extra row or not clearing properly

(reported by dixonary)

**Comment by raisjn** [comment]
i think https://github.com/rmkit-dev/rmkit/commit/c3c164ca31e69cee8a6614d0003390287c0c0fa6 will fix it

**Comment by mrichards42** [comment]
I also noticed this in in remarkable_puzzles and assumed I was doing something funny w/ alignment or redrawing, but this seems to have fixed it!

**Comment by raisjn** [comment]
on a related note, a fix for rendering 8 bit grayscale images went in, which should fix the strange rendering of some bitmaps (i saw the swap of two components in puzzles repo in torgb 565 function)

**Comment by mrichards42** [comment]
I was swapping the bytes in rgb565 b/c it made some of the colors look better (and b/c I assumed the bytes would have been written to the framebuffer backwards though it didn't occur to me at the time that it's probably a LE processor). Turns out the default colors just don't translate to grayscale very well, so I undid that and have been working on customizing colors game-by-game.

**Comment by raisjn** [comment]
this is in the current stable merge window of toltec, gonna close for now
