### ISSUE TITLE
[remux] Suspend weirdness, image bad resolution/quality

### ISSUE THREAD

**Issue by notDavid** [rmkit-dev/rmkit#54]
Hi there,

FYI i noticed some weirdness on my remarkable2 with suspending after installing reumx;

1. It seems my remarkable2 will sometimes go to suspend much faster (like 3 minutes) than before i installed remux (~ 15 minutes.) 

2. Most of the time the suspend image is really bad quality. Like for example it is only 300 pixels or something instead of 4000.  But this does not always seem to be the case, sometimes it is the normal/proper image quality.

3. When suspend happens after 4 minutes (and i then see the bad resolution suspend image), and i click the button to wake up the rm2 again, it wakes up but only for about 10 seconds, then it will immediately go back to the suspend image again. This repeats, until i do some activity like writing or something.

```
reMarkable: ~/ opkg list_installed | grep -i remux
remux - 0.1.5-1
```

PS. When using the button to suspend my rm2, the suspend image quality is always good.

**Comment by raisjn** [comment]
thanks for the detailed bug report, i really appreciate it!

> 1. It seems my remarkable2 will sometimes go to suspend much faster (like 3 minutes) than before i installed remux (~ 15 minutes.) 

you can fix this by editing the xochitl.conf and setting `IdleSuspendDelay` to a higher value (see https://remarkablewiki.com/tips/suspendtime). if this value is unset, remux uses 4 minutes by default. is there a way this can be improved for you? (do you want the config in remux.conf? do you want remux to use same default? the default in remux was lowered because rM1 is worse with battery life than rM2)

> 2. Most of the time the suspend image is really bad quality. Like for example it is only 300 pixels or something instead of 4000.  But this does not always seem to be the case, sometimes it is the normal/proper image quality.

can you link your suspend image and can you take a picture of what you mean by bad resolution? (does it mean that the image isn't being resized or does it mean the colors are wrong, etc). for testing purposes, i can make a binary that sets the screen to an image using the same routines as remux and we'll see if it paints correctly. 

> 3. When suspend happens after 4 minutes (and i then see the bad resolution suspend image), and i click the button to wake up the rm2 again, it wakes up but only for about 10 seconds, then it will immediately go back to the suspend image again. This repeats, until i do some activity like writing or something.

this sounds like remux isn't properly resetting the suspend timer when a button press is received. i believe  a46fa08fa97e0f756096983f98574d793a3ca145 will fix this. you can try the remux binary from https://build.rmkit.dev/master/latest/files/ (make sure to chmod +x it) to see if this fixes it.

**Comment by notDavid** [comment]
Hi @raisjn, thanks for your reply;

1. Okay great, if there's a setting that's perfectly fine with me. I will change the `IdleSuspendDelay` back to the default setting.

2. Here's the original image and 2 pictures, the correct one when i press the power button, and the weird one when it goes to suspend automatically. Now that i look at it again, it looks like the "colors" are inverted...?

- [Screenshot-auto](https://user-images.githubusercontent.com/1530401/105198331-776da200-5b35-11eb-94d0-e507c82c3cb7.png)
 
- [Screenshot-button-pressed](https://user-images.githubusercontent.com/1530401/105198475-9bc97e80-5b35-11eb-8065-ae1181d057bd.png)

- [original-image-suspended](https://user-images.githubusercontent.com/1530401/105198554-aab03100-5b35-11eb-98bf-3262ac97750a.png)

3. Okay, i will test this later...

**Comment by raisjn** [comment]
perfect, you gave me enough to debug part 2. i think you are right: the colors are coming out wrong (and maybe R is swapped with G or similar)

**Comment by raisjn** [comment]
thanks for the test image, it helped! the issue was that the image you are using is a 8 bit grayscale and remux didn't know how to handle those properly. i updated remux to support 8bit grayscale images. a new binary should be available on build.rmkit.dev (same as the URL above)

this fix will likely make it into toltec testing this week and hopefully be in stable in the next merge window (next week)

**Comment by notDavid** [comment]
Thank you for the quick fix! :-)

**Comment by jonahweissman** [comment]
> > 1. It seems my remarkable2 will sometimes go to suspend much faster (like 3 minutes) than before i installed remux (~ 15 minutes.)
> 
> you can fix this by editing the xochitl.conf and setting `IdleSuspendDelay` to a higher value (see https://remarkablewiki.com/tips/suspendtime). if this value is unset, remux uses 4 minutes by default. is there a way this can be improved for you? (do you want the config in remux.conf? do you want remux to use same default? the default in remux was lowered because rM1 is worse with battery life than rM2)

I think it would make more sense for remux to use the same default as xochitl. As a new remux user (on rM2), it was kinda jarring to have the suspend time change so dramatically without me having chosen that. If it's important to let rM1 users know that they can lower the sleep time, maybe there could be a link to the wiki in the remux README.

**Comment by raisjn** [comment]
> I think it would make more sense for remux to use the same default as xochitl. As a new remux user (on rM2), it was kinda jarring to have the suspend time change so dramatically without me having chosen that. If it's important to let rM1 users know that they can lower the sleep time, maybe there could be a link to the wiki in the remux README.

sounds reasonable to me
