### ISSUE TITLE
[remux] Please update package in Toltec to latest version

### ISSUE THREAD

**Issue by jdkruzr** [rmkit-dev/rmkit#66]
I think the version in Toltec right now is quite old. Toltec has 0.1.5-1 and I think there have been a number of feature updates since (e.g. 0.1.5-1 still launches on my rM2 with three-finger tap, which I gather you removed for some reason since). I can tell you have updated to at least 0.1.7, but AFAICT there is no way to determine what your current version number is from the repo.

**Comment by raisjn** [comment]
the process for promoting a package from testing -> stable takes a little while. you can get 0.1.7-3 from https://toltec-dev.org/testing/remux_0.1.7-3_armv7-3.2.ipk, though. 

this past week, 0.1.6 was up for inclusion in stable (from testing) but the merge hasn't happened yet. 0.1.7 is now in testing and will be up for merge starting monday.

three finger tap was removed because it launches too easily: it's better that people choose their own launch gesture.

**Comment by jdkruzr** [comment]
thank you!
