### ISSUE TITLE
[genie/remux] Can't launch remux easily after closing

### ISSUE THREAD

**Issue by marcoms** [rmkit-dev/rmkit#82]
Every time I close remux, the first gesture to open it again always fails. It's like it needs me to interact with xioctl before it recognizes a gesture.

See demo video: https://photos.app.goo.gl/DKe2UQaDKvaoakCW6

**Comment by raisjn** [comment]
thank you for reporting! i have known about this but haven't gotten to fixing it yet since it should occur infrequently unless you are testing remux's swipe gesture. (i actually thought the swipe was only 50% accurate at first and was disappointed until i realized this bug was happening)

it is likely something to do with how remux and how multi-touch event handling works - the rmkit event system has been getting overhauled, so hopefully we can fix this along the way.

**Comment by raisjn** [comment]
i'm starting to look into this more and try to make it very reliable to launch remux, thanks for the patience

**Comment by raisjn** [comment]
another problem that might be related is: after drawing with stylus, remux required a touch tap before the gestures would work again. this is fixed in recent commit https://github.com/rmkit-dev/rmkit/commit/e8549b683c37fad3effcbed00be9fed3ef556ba7

**Comment by raisjn** [comment]
the original issue (can't launch after closing) is addressed in eb778449faee4673167939c126b8aa21d07198ad

now i can launch remux immediately after closing it. @marcoms - if you have time, please try out the remux in https://build.rmkit.dev/master/latest/files (remember to `chmod +x remux` after installing it). i will try to get it into toltec's testing repository in the coming few days (and into stable merge the week after that)

again, thanks for the video and reporting - it motivated me to fix this problem.

**Comment by raisjn** [comment]
this is now in toltec testing and should be included in the next stable merge
